### ISSUE TITLE
No need to use btnAdd after textbox

### ISSUE THREAD

**Issue by webframing** [arafatamim/online-todo#1]
It seems that there is no use of the button that is just after the textbox i.e `#btnAdd` as it is hidden and is not focusable also:
```html
<button id="btnAdd">+</button>
```
Nevertheless it is used in js file:
```javascript
$("#btnAdd").click(function () {
  addNote();
});
```

**Comment by arafatamim** [comment]
You're right. I just added this for testing purposes and forgot to remove it later. Will be fixed soon :-)
